### ISSUE TITLE
Key-combo ctrl+a not working

### ISSUE THREAD

**Issue by dianaprajescu** [j-ulrich/jquery-simulate-ext#30]
I'm not sure if ctrl+a is supposed to work, but I think it's a pretty common key combination. here is a jsfiddle for you to test: http://jsfiddle.net/Psjhf/723/

**Comment by j-ulrich** [comment]
Yeah. The plugin cannot trigger default behavior of browsers (like ctrl+a, ctrl+c, ctrl+v etc.) and I'd say it is out of scope to simulate that behavior, especially because the shortcuts could be different depending on browser, operating system and/or user preferences.

Nevertheless, it is possible to simulate a "select all" using the [`{selectall}` special sequence of the key-sequence plugin](https://github.com/j-ulrich/jquery-simulate-ext/blob/master/doc/key-sequence.md#special-sequences).
