### ISSUE TITLE
i can simulate "ctrl" pressed ?

### ISSUE THREAD

**Issue by iwacham** [j-ulrich/jquery-simulate-ext#35]
i can simulate this ?
on mouseover event simulate ctrl pressed to open a link on new tab

the reason is the link is on iframe.

**Comment by j-ulrich** [comment]
You can simulate the <kbd>Ctrl</kbd> key being pressed like this (i assume you rather want a [`click`](https://developer.mozilla.org/en-US/docs/Web/Events/click) event instead of a [`mouseover`](https://developer.mozilla.org/en-US/docs/Web/Events/mouseover)):
```javascript
$('#myEle').simulate('click', { ctrlKey: true })
```
However, this will most likely **not** open a link in a new tab unless the website explicitly implements that via `window.open()` or similar. The reason for this is that simulated events do **not** trigger browser behavior but only website behavior. That means you can trigger behavior which has been defined via JavaScript (for example with `$('#myEle').on('click', /*...*/)`) or behavior of the DOM but not behavior the browser adds on top of that (like opening in new tab/window).
